//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveBankExpense
    {
        public int Id { get; set; }
        public Nullable<int> StatementId { get; set; }
        public Nullable<int> AccountantId { get; set; }
        public string AccountantEmail { get; set; }
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> BillTax { get; set; }
        public Nullable<decimal> BillTotal { get; set; }
        public string AccountType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AccountNumber { get; set; }
        public string Expense { get; set; }
        public string Status { get; set; }
        public string TransactionType { get; set; }
        public string Purpose { get; set; }
        public string Vendor { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Category { get; set; }
        public string Comments { get; set; }
        public string AccountName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> ClassificationId { get; set; }
        public string Classification { get; set; }
        public Nullable<bool> IsDownload { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<decimal> GSTtax { get; set; }
        public Nullable<decimal> QSTtax { get; set; }
        public Nullable<decimal> HSTtax { get; set; }
        public Nullable<decimal> PSTtax { get; set; }
        public Nullable<int> AccountClassificationId { get; set; }
        public string FriendlyName { get; set; }
    }
}
