//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.BankExpenses = new HashSet<BankExpense>();
        }
    
        public int Id { get; set; }
        public string BankName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string BankType { get; set; }
        public string BankCode { get; set; }
    
        public virtual ICollection<BankExpense> BankExpenses { get; set; }
    }
}
