//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankExpense
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> BankId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> ActualTotal { get; set; }
        public Nullable<decimal> GSTtax { get; set; }
        public Nullable<decimal> QSTtax { get; set; }
        public Nullable<decimal> HSTtax { get; set; }
        public Nullable<decimal> PSTtax { get; set; }
        public Nullable<decimal> GSTPercentage { get; set; }
        public Nullable<decimal> QSTPercentage { get; set; }
        public Nullable<decimal> HSTPercentage { get; set; }
        public Nullable<decimal> PSTPercentage { get; set; }
        public Nullable<double> ActualPercentage { get; set; }
        public string AccountType { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ClassificationId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string TransactionType { get; set; }
        public string Purpose { get; set; }
        public string Vendor { get; set; }
        public string Comments { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string UploadedStatementName { get; set; }
        public string UploadType { get; set; }
        public Nullable<int> AccountClassificationId { get; set; }
        public Nullable<long> TransactionId { get; set; }
        public Nullable<long> AccountId { get; set; }
        public bool IsYodlee { get; set; }
        public Nullable<bool> IsVirtualEntry { get; set; }
        public Nullable<int> StatementReferenceNumber { get; set; }
        public Nullable<int> JVID { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Category Category { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
        public virtual Classification Classification { get; set; }
    }
}
