//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classification
    {
        public Classification()
        {
            this.BankExpenses = new HashSet<BankExpense>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string ClassificationType { get; set; }
        public int ChartAccountNumber { get; set; }
        public string ChartAccountDisplayNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsSole { get; set; }
        public Nullable<bool> IsIncorporated { get; set; }
        public Nullable<bool> IsPartnerShip { get; set; }
        public string Desc { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> SubIndustryId { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public Nullable<int> ReportingSubTotalNumber { get; set; }
        public string ReportingSubTotalDisplayNumber { get; set; }
        public Nullable<int> ReportingTotalNumber { get; set; }
        public string ReportingTotalDisplayNumber { get; set; }
        public string RangeofAct { get; set; }
        public string CategoryValue { get; set; }
    
        public virtual ICollection<BankExpense> BankExpenses { get; set; }
    }
}
