//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectorAccountLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> PercentageAmount { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public int StatementId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
