//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterClassification
    {
        public int Id { get; set; }
        public string ReportingTotal { get; set; }
        public string RepotingTotalType { get; set; }
        public string ReportingTotalRange { get; set; }
        public string NewClassificationVerb { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string SubTotalDisplayNumber { get; set; }
        public string TotalDisplayNumber { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
