//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public byte Id { get; set; }
        public string ProvinceName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
