//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.BankExpenses = new HashSet<BankExpense>();
        }
    
        public int Id { get; set; }
        public string StatusType { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<BankExpense> BankExpenses { get; set; }
    }
}
