//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubAccountantUserPermission
    {
        public int Id { get; set; }
        public Nullable<int> AccountantId { get; set; }
        public int SubAccountantId { get; set; }
        public int UserWithAnAccountantId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
