//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemDetail
    {
        public int Id { get; set; }
        public string ServiceType { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Item { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string Discount { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> Customer_ServiceTypeId { get; set; }
        public string Customer_Service { get; set; }
        public string Tax { get; set; }
        public string GST_Tax { get; set; }
        public string HST_Tax { get; set; }
        public string PST_Tax { get; set; }
        public string QST_Tax { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
    }
}
