//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblT1TypeCategories
    {
        public int T1Id { get; set; }
        public string T1Name { get; set; }
        public Nullable<int> T1CategoryId { get; set; }
        public Nullable<int> T1Values { get; set; }
    }
}
