//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblZTypeCategory
    {
        public int ZId { get; set; }
        public string ZName { get; set; }
        public Nullable<int> ZCategoryId { get; set; }
        public Nullable<int> ZValues { get; set; }
    }
}
