//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserUpdateProfileLog
    {
        public int Id { get; set; }
        public string FieldUpdatedDetails { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsSuperAdminUpdated { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsPasswordUpdated { get; set; }
        public Nullable<bool> IsLogin { get; set; }
    }
}
