//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegistration
    {
        public UserRegistration()
        {
            this.UserLincensePayments = new HashSet<UserLincensePayment>();
            this.BankExpenses = new HashSet<BankExpense>();
            this.SubAccountantUserPermissions = new HashSet<SubAccountantUserPermission>();
        }
    
        public int Id { get; set; }
        public Nullable<byte> ReconciliationType { get; set; }
        public Nullable<int> AccountantId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<byte> ProvinceId { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> SubIndustryId { get; set; }
        public string CompanyName { get; set; }
        public string CorporationAddress { get; set; }
        public string GSTNumber { get; set; }
        public string BusinessNumber { get; set; }
        public Nullable<int> OwnershipId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> LicenseId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string PrivateKey { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsTrial { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<int> TaxationStartDay { get; set; }
        public Nullable<int> TaxationEndDay { get; set; }
        public Nullable<byte> TaxStartMonthId { get; set; }
        public Nullable<byte> TaxEndMonthId { get; set; }
        public Nullable<int> TaxStartYear { get; set; }
        public Nullable<int> TaxEndYear { get; set; }
        public bool IsDownload { get; set; }
        public Nullable<bool> IsNewUser { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsUnlink { get; set; }
        public Nullable<bool> IsTermsAndConditionAccepted { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<bool> IsYodleeAccountCreated { get; set; }
        public string Country { get; set; }
        public Nullable<bool> IsEmployeeActivated { get; set; }
        public Nullable<bool> IsOnlyInvoice { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<bool> IsLoggedInWeb { get; set; }
        public Nullable<bool> IsLoggedInMobile { get; set; }
    
        public virtual ICollection<UserLincensePayment> UserLincensePayments { get; set; }
        public virtual ICollection<BankExpense> BankExpenses { get; set; }
        public virtual ICollection<SubAccountantUserPermission> SubAccountantUserPermissions { get; set; }
    }
}
