//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YodleeUserRegistration
    {
        public int Id { get; set; }
        public string UName { get; set; }
        public string UPassword { get; set; }
        public string CobrandName { get; set; }
        public string CobrandPassword { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> KippinUserId { get; set; }
    }
}
